import type { Trip } from "@/lib/types/trip";

const t0 = new Date().toISOString();

export const sampleTrip: Trip = {
  id: "sample-1",
  title: "Bangkok long weekend",
  description: "Canonical-model sample trip",
  currency: "THB",
  travelers: [
    { id: "tr-1", name: "Alex", email: "alex@example.com", role: "owner" },
    { id: "tr-2", name: "Sam", role: "editor" },
  ],
  viewers: [{ id: "vw-1", name: "Jordan", email: "jordan@example.com" }],
  startDate: "2026-06-01T14:00:00.000Z",
  endDate: "2026-06-05T11:00:00.000Z",
  destinations: [
    {
      id: "dest-bkk",
      title: "Bangkok",
      location: "Sukhumvit, Bangkok",
      description: "Bangkok, Thailand",
      coordinates: { lat: 13.7373, lon: 100.5607 },
    },
    {
      id: "dest-ko",
      title: "Koh Samet",
      location: "Na Dan pier area",
      description: "Rayong Province, Thailand",
      coordinates: { lat: 12.5657, lon: 101.4518 },
    },
    {
      id: "dest-snorkel",
      title: "East coast reef",
      location: "Koh Samet",
      description: "Koh Samet, Thailand",
    },
  ],
  budget: {
    totalBudget: { amount: 45000, currency: "THB" },
    categories: {
      hotels: { amount: 18000, currency: "THB" },
      transport: { amount: 12000, currency: "THB" },
      food: { amount: 8000, currency: "THB" },
      activities: { amount: 7000, currency: "THB" },
    },
  },
  tasks: [
    {
      id: "task-1",
      title: "Book airport van",
      status: "todo",
      dueDate: "2026-05-20T12:00:00.000Z",
    },
  ],
  documents: [],
  warnings: [],
  packingLists: [
    {
      id: "pack-1",
      title: "Bangkok long weekend",
      templateId: "tpl-beach-weekend",
      items: [
        { id: "p-doc-1", name: "Passport", category: "documents", packed: true },
        { id: "p-doc-2", name: "Travel insurance card", category: "documents", packed: false },
        { id: "p-clo-1", name: "Linen shirts", category: "clothes", quantity: 3, packed: false },
        { id: "p-clo-2", name: "Swimsuit", category: "clothes", quantity: 2, packed: true },
        { id: "p-toi-1", name: "Reef-safe sunscreen", category: "toiletries", packed: false },
        { id: "p-tec-1", name: "Universal adapter", category: "tech", packed: true },
        { id: "p-hea-1", name: "Mosquito repellent", category: "health", packed: false },
        { id: "p-gear-1", name: "Snorkel mask", category: "gear", packed: false },
      ],
    },
  ],
  expenses: [
    {
      id: "exp-1",
      title: "City hotel · 3 nights",
      amount: { amount: 12500, currency: "THB" },
      paidByTravelerId: "tr-1",
      splitBetween: ["tr-1", "tr-2"],
      category: "hotels",
      date: "2026-06-01T15:00:00.000Z",
      relatedStepId: "st-1",
    },
    {
      id: "exp-2",
      title: "Van + ferry tickets",
      amount: { amount: 1800, currency: "THB" },
      paidByTravelerId: "tr-2",
      splitBetween: ["tr-1", "tr-2"],
      category: "transport",
      date: "2026-06-04T12:30:00.000Z",
      relatedStepId: "step-transit-1",
    },
    {
      id: "exp-3",
      title: "Snorkel boat",
      amount: { amount: 2200, currency: "THB" },
      paidByTravelerId: "tr-1",
      splitBetween: ["tr-1", "tr-2"],
      category: "activities",
      date: "2026-06-05T08:00:00.000Z",
      relatedStepId: "ac-1",
    },
    {
      id: "exp-4",
      title: "Street food dinner",
      amount: { amount: 650, currency: "THB" },
      paidByTravelerId: "tr-2",
      splitBetween: ["tr-1", "tr-2"],
      category: "food",
      date: "2026-06-02T13:00:00.000Z",
    },
  ],
  comments: [
    {
      id: "c-1",
      authorId: "alex@example.com",
      authorName: "Alex",
      createdAt: "2026-05-15T09:00:00.000Z",
      body: "Should we add a Wat Pho visit on day 2 morning? It is a 10-min tuk-tuk away.",
      targetType: "trip",
      targetId: "sample-1",
      reactions: ["jordan@example.com"],
    },
    {
      id: "c-2",
      authorId: "jordan@example.com",
      authorName: "Jordan",
      createdAt: "2026-05-15T09:30:00.000Z",
      body: "+1 — and please pick a sunset rooftop somewhere. I'll vote.",
      targetType: "trip",
      targetId: "sample-1",
      parentId: "c-1",
    },
  ],
  recommendationVotes: [],
  weatherCache: [],
  steps: [
    {
      id: "st-1",
      order: 0,
      stepType: "stay",
      title: "Sukhumvit base",
      startTime: "2026-06-01T15:00:00.000Z",
      endTime: "2026-06-04T11:00:00.000Z",
      targetDestinationId: "dest-bkk",
      stepIntervals: [
        {
          id: "int-1",
          intervalType: "stay",
          stayType: "hotel",
          title: "City hotel",
          startTime: "2026-06-01T15:00:00.000Z",
          endTime: "2026-06-04T11:00:00.000Z",
          checkInTime: "2026-06-01T15:00:00.000Z",
          checkOutTime: "2026-06-04T11:00:00.000Z",
          nights: 3,
          location: "Sukhumvit Soi 24",
          booking: {
            status: "reserved",
            bookingUrl: "https://example.com",
          },
          price: { amount: 12000, currency: "THB" },
        },
      ],
    },
    {
      id: "step-transit-1",
      order: 1,
      stepType: "transit",
      title: "To islands",
      startTime: "2026-06-04T12:30:00.000Z",
      endTime: "2026-06-04T16:00:00.000Z",
      fromStayId: "dest-bkk",
      toStayId: "dest-ko",
      targetDestinationId: "dest-ko",
      stepIntervals: [
        {
          id: "int-tr-1",
          intervalType: "transit",
          transitType: "speed_boat",
          title: "Van + ferry",
          startTime: "2026-06-04T12:30:00.000Z",
          endTime: "2026-06-04T16:00:00.000Z",
          fromDestinationId: "dest-bkk",
          toDestinationId: "dest-ko",
          price: { amount: 1800, currency: "THB" },
        },
      ],
    },
    {
      id: "ac-1",
      order: 2,
      stepType: "activity",
      title: "Snorkel trip",
      startTime: "2026-06-05T08:00:00.000Z",
      endTime: "2026-06-05T11:00:00.000Z",
      destinationId: "dest-snorkel",
      targetDestinationId: "dest-snorkel",
      hostStayStepId: "st-1",
      stepIntervals: [
        {
          id: "int-ac-1",
          intervalType: "activity",
          activityType: "snorkeling",
          title: "Half-day boat",
          startTime: "2026-06-05T08:00:00.000Z",
          endTime: "2026-06-05T11:00:00.000Z",
          destinationId: "dest-snorkel",
          price: { amount: 4500, currency: "THB" },
        },
      ],
    },
  ],
  createdAt: t0,
  updatedAt: t0,
};
